[pytest]
minversion = 8.0
addopts = 
    -v
    --tb=short
    -n auto
    --dist=loadscope
    --alluredir=allure-results
    --clean-alluredir
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: быстрая проверка критического функционала
    api: тесты API
    slow: медленные тесты
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
