apiVersion: v1
kind: Secret
metadata:
  name: api-tests-secrets
  namespace: default
type: Opaque
stringData:
  ENV: "prod"
  BASE_URL: "https://api.hh.ru"
  # Добавьте свои секреты здесь при необходимости
